version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /path/on/host:/data/db
    networks:
      - gotnetwork

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7094:80"
      #- "7094:443"
    networks:
      - gotnetwork
    environment:
      #- VIRTUAL_HOST=sub.domain-example.com
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certificates:/etc/certificates
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  certificates:
networks:
  gotnetwork:
